POST http://localhost:3000/register 
Content-Type: application/json

{
  "username": "ajay",
  "name": "Ajay Kumar",
  "password": "ajay@123",
  "gender": "male",
  "location": "Vja"
}
### 
POST http://localhost:3000/login
Content-Type: application/json 

{
  "username": "ajay",
  "password": "ajay@123"
}
### 
PUT http://localhost:3000/change-password 
Content-Type: application/json 

{
  "username": "ajay",
  "oldPassword": "ajay@123",
  "newPassword": "ajay_123"
}